releases:
  - name: langgraph-cloud
    chart: ./langgraph-cloud
    namespace: dev

  - name: postgres
    chart: ./postgres
    namespace: dev
  
  - name: pgadmin
    chart: ./pgadmin
    namespace: dev

  - name: elastic
    chart: ./elastic
    namespace: dev

  - name: kibana
    chart: ./kibana
    namespace: dev

  # for local testing
   
  # - name: ai-agents
  #   chart: ./microservices/ai-agents

  # - name: nginx
  #   chart: ./microservices/nginx

  # - name: apple
  #   chart: ./microservices/apple

  # - name: pear
  #   chart: ./microservices/pear

  # - name: movies
  #   chart: ./microservices/movies

  # - name: fastapi
  #   chart: ./microservices/fastapi


