apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9300
    targetPort: 9300
    name: transport
  selector:
    app: elasticsearch
