apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres
