apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: dev
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: postgres
  ports:
  - port: 5432
    targetPort: 5432
