apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/postgres-data  # Create: sudo mkdir -p /tmp/postgres-data; sudo chmod 777 /tmp/postgres-data
